<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Rocco Petrongolo by petronr1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">Rocco Petrongolo</h1>
      <h2 class="project-tagline">Italian American Cyborg</h2>
    </section>

    <section class="main-content">
      <h3>
<a id="diagnostics" class="anchor" href="#diagnostics" aria-hidden="true"><span class="octicon octicon-link"></span></a>Diagnostics</h3>

<p>Healthy. Up and Running</p>

<h3>
<a id="my-programs" class="anchor" href="#my-programs" aria-hidden="true"><span class="octicon octicon-link"></span></a>My Programs</h3>

<p>PHP, Java, C++, JavaScript, HTML, CSS, Adobe Photoshop, Weight-lifting, Soccer, Music</p>

<h3>
<a id="my-platforms--environments" class="anchor" href="#my-platforms--environments" aria-hidden="true"><span class="octicon octicon-link"></span></a>My Platforms &amp; Environments</h3>

<p>Terminal, Wordpress, Bootstrap, Xcode, AWS (EC2, S3, RDS), Linux , FileZilla, Vim, TextWrangler, Pacific Beach, Sunset Cliffs, the Gym</p>

<h3>
<a id="github" class="anchor" href="#github" aria-hidden="true"><span class="octicon octicon-link"></span></a>GitHub</h3>

<p>(<a href="https://github.com/petronr1" class="user-mention">@petronr1</a>).</p>

<h3>
<a id="support-or-contact" class="anchor" href="#support-or-contact" aria-hidden="true"><span class="octicon octicon-link"></span></a>Support or Contact</h3>

<p>Shoot me a phone call, txt or email me rpetrong1-at-gmail</p>

      <footer class="site-footer">

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>

  
  </body>
</html>

